### ISSUE TITLE
Only usable as CLI script?

### ISSUE THREAD

**Issue by spaceone** [kyrias/vic#1]
It seems this is only a CLI script. It would be nice if this can be used as regular python module.

**Comment by spaceone** [comment]
It's not even executable:
```$ python3 /usr/local/lib/python3.4/dist-packages/vic/main.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/vic/main.py", line 4, in <module>
    from .encrypt import encrypt
SystemError: Parent module '' not loaded, cannot perform relative import
```

Workaround:

`python3 -c 'import vic.main; vic.main.main()' encrypt -h`

**Comment by kyrias** [comment]
It's just meant to be a CLI tool as it is, and it works just fine, it's just a module that's supposed to be installed.

It would be pretty easy to  make it easily usable as a lib though, would essentially just need to lift the content of the `args` argument to `encrypt`/`decrypt` out into proper function parameters instead.

What exactly where you thinking of using it for though?

**Comment by kyrias** [comment]
... Though I've just found some weird bugs which are making me question how it worked before.

**Comment by kyrias** [comment]
@spaceone I've finished my rewrite, and now it should be usable both through directly executing the module (`python -m vic`), or through the script or as a library after installing the module with pip.
