### ISSUE TITLE
Trouble running the project

### ISSUE THREAD

**Issue by ArcanamTredecim** [kyrias/vic#11]
Hey, I tried running the code but I'm having trouble where it's giving me the following :
![11](https://user-images.githubusercontent.com/72079190/98966915-e8cd1b00-251c-11eb-8478-7b8be8248748.PNG)

**Comment by saadbitar1998** [comment]
I'm facing the same problem. Please HELP!!

**Comment by kyrias** [comment]
It's a CLI tool, so there's no reasonable way to use the `main` function from an IDE.

Either run the module from a terminal, or write your own scripts that use the `encrypt`/`decrypt` functions.
